### PR TITLE
formatting using `black`

### PR DESCRIPTION
**Pull request by UltraStudioLTD**
I ran `black` formatting tool which formatted entire project (Python files only)

### CODE REVIEW

**Comment by UltraStudioLTD** [comment]
Also please use `pylint` to improve code quality. This is optional but recommended for various reasons including security, optimisation and readability

**Comment by UltraStudioLTD** [comment]
Alright. Then I will close this PR

**Comment by UltraStudioLTD** [comment]
But what about making this a step before releasing? I mean that during development what you are doing (aligning) is making it more readable but after installing module it just wastes space and lines in source code, so change `setup.py` or anything to temporarily copy source code somewhere, format it and install that and delete it. Only problem is that this method will double size the source code but that's not a big problem nowadays (I mean we are not in 70-80s)

**Comment by ceccopierangiolieugenio** [comment]
Yes it is doable, I already run some scripts to change the code before the release
i.e. the version is added during the release. ([prepareBuild.sh](https://github.com/ceccopierangiolieugenio/pyTermTk/blob/main/tools/prepareBuild.sh))
anyway, few spaces here and there are not making a big difference, just think about the comments or long function names that is basically wasted space, 
I will make a test anyway to check the differences with or without formatting, 
anyway, except this minor things I will start using more strict rules for the code.
Thanks

**Comment by UltraStudioLTD** [comment]
No problem

**Pull request closed without merging**
